/*
 * JTagEditor.java
 *
 * Created on 27 septembre 2007, 19:46
 */

package jsesh.utilitySoftwares.signInfoEditor.ui;

/**
 *
 * @author  rosmord
 */
public class JTagEditor extends javax.swing.JPanel {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 2253271717049260331L;

	/** Creates new form JTagEditor */
    public JTagEditor() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tagNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tagNameList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelTable = new javax.swing.JTable();
        labelAddButton = new javax.swing.JButton();
        labelRemoveButton = new javax.swing.JButton();
        tagAddButton = new javax.swing.JButton();
        tagRemoveButton = new javax.swing.JButton();
        labelField = new javax.swing.JTextField();

        tagNameField.setColumns(10);

        jLabel1.setText("Tag");

        tagNameList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(tagNameList);

        jLabel2.setText("Tag labels");

        labelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(labelTable);

        labelAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jsesh/utilitySoftwares/signInfoEditor/icons/edit_add.png"))); // NOI18N

        labelRemoveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jsesh/utilitySoftwares/signInfoEditor/icons/edit_remove.png"))); // NOI18N

        tagAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jsesh/utilitySoftwares/signInfoEditor/icons/edit_add.png"))); // NOI18N

        tagRemoveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jsesh/utilitySoftwares/signInfoEditor/icons/edit_remove.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(tagNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(tagRemoveButton, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(tagAddButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelAddButton)
                    .add(labelRemoveButton))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {labelAddButton, labelRemoveButton, tagAddButton, tagRemoveButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(tagNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tagAddButton)
                    .add(jLabel2)
                    .add(labelField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelAddButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .add(tagRemoveButton)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .add(labelRemoveButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton labelAddButton;
    private javax.swing.JTextField labelField;
    private javax.swing.JButton labelRemoveButton;
    private javax.swing.JTable labelTable;
    private javax.swing.JButton tagAddButton;
    private javax.swing.JTextField tagNameField;
    private javax.swing.JList tagNameList;
    private javax.swing.JButton tagRemoveButton;
    // End of variables declaration//GEN-END:variables

	/**
	 * @return the labelAddButton
	 */
	public javax.swing.JButton getLabelAddButton() {
		return labelAddButton;
	}

	/**
	 * @return the labelField
	 */
	public javax.swing.JTextField getLabelField() {
		return labelField;
	}

	/**
	 * @return the labelRemoveButton
	 */
	public javax.swing.JButton getLabelRemoveButton() {
		return labelRemoveButton;
	}

	/**
	 * @return the labelTable
	 */
	public javax.swing.JTable getLabelTable() {
		return labelTable;
	}

	/**
	 * @return the tagAddButton
	 */
	public javax.swing.JButton getTagAddButton() {
		return tagAddButton;
	}

	/**
	 * @return the tagNameField
	 */
	public javax.swing.JTextField getTagNameField() {
		return tagNameField;
	}

	/**
	 * @return the tagNameList
	 */
	public javax.swing.JList getTagNameList() {
		return tagNameList;
	}

	/**
	 * @return the tagRemoveButton
	 */
	public javax.swing.JButton getTagRemoveButton() {
		return tagRemoveButton;
	}
    
}
