package jsesh.mdcDisplayer.draw;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import javax.imageio.ImageIO;

import org.junit.Test;

import jsesh.drawingspecifications.JSeshStyle;
import jsesh.mdc.MDCSyntaxError;

/**
 * Helper class to manage picture drawing tests.
 */
public class TestPictureFilesHelper {
    private TestPictureFilesHelper() {
    }

    /**
     * Path to the directory where pictures generated by tests are stored.
     * <p>
     * Note that the unix separator is also understood on windows, so we don't need
     * to be fussy about it.
     */
    private static final Path PICTURE_OUTPUT_DIRECTORY = Path.of("reports", "pictures");

    private static Path buildDir() {
        return Path.of(System.getProperty("buildDir", "build"));
    }

    private static Path pictureOutputDirectory() {
        return buildDir().resolve(PICTURE_OUTPUT_DIRECTORY);
    }


    /**
     * Returns the path for a picture file generated by a test.
     * 
     * @param fileName the name of the picture file (without suffix).
     * @param suffix   the suffix (without '.')
     * @return
     */
    private static Path getPicturePath(String fileName, String suffix) {
        if (suffix.startsWith(".")) {
            throw new IllegalArgumentException("Suffix should not start with a dot.");
        }
        return pictureOutputDirectory().resolve(fileName + "." + suffix);
    }

    /**
     * Perform some code to create a picture in the picture folder, and pass the
     * path to the picture to the consumer.
     * 
     * <p>
     * This code ensures that the picture folder exists before calling the consumer.
     * 
     * @param fileName the name of the picture file (without suffix).
     * @param suffix   the suffix (without '.')
     * @param consumer the code which will create the picture. The path to the
     *                 picture file will be passed to it.
     */
    public static void doWithPicturePath(String fileName, String suffix, java.util.function.Consumer<Path> consumer) {
        try {
            Path picturePath = getPicturePath(fileName, suffix);
            Files.createDirectories(picturePath.getParent());
            consumer.accept(picturePath);
        } catch (Exception e) {
            throw new RuntimeException("I/O Problem occurred: ", e);
        }
    }

    /**
     * Check drawing of a picture, saved in the build/reports/pictures folder.
     * @param mdc manuel de codage string to draw
     * @param fileName the file name (without suffix) of the picture to create.
     * @param jSeshStyle the style to use for drawing.
     * @throws MDCSyntaxError
     * @throws IOException
     */
    public static void drawInPicture(String mdc, String fileName, JSeshStyle jSeshStyle)  {
        MDCDrawingFacade facade = MDCDrawingFacade.buildDefault();
        facade.setStyle(jSeshStyle);
        TestPictureFilesHelper.doWithPicturePath(fileName, "png", path -> {
            try {
                BufferedImage image = facade.createImage(mdc);
                ImageIO.write(image, "png", path.toFile());
            } catch (IOException | MDCSyntaxError e) {
                throw new RuntimeException(e);
            }
        });
    }
}
