package jsesh.parser.lex;

/**
 * Token identifiers for the Manuel de Codage lexer ({@link MDCLexAux}) and
 * parser ({@link jsesh.parser.handmade.MDCHandmadeParser}).
 * <p>Used to be generated by CUP from the terminal declarations in
 * {@code jsesh/src/jcup/MDCParse.y}; now hand-maintained, with the same
 * values, now that the grammar is a hand-written recursive descent parser
 * instead.
 */
public interface MDCSymbols {
    /* terminals */
    int HIEROGLYPH = 12;
    int BEGINOLDCARTOUCHE = 4;
    int CADRAT = 43;
    int OVERWRITE = 15;
    int TABBING = 19;
    int TOGGLE = 27;
    int INTEGER = 32;
    int MODIFIER = 14;
    int STAR = 24;
    int TEXTSUPER = 26;
    int WORDEND = 28;
    int BEGINCARTOUCHE = 3;
    int GRAMMAR = 11;
    int COMMA = 33;
    int SEPARATOR = 22;
    int TABSTOP = 18;
    int DOUBLEAMP = 34;
    int PAGEEND = 16;
    int DOUBLELEFTCURLY = 37;
    int EOF = 0;
    int AMP = 2;
    int EQUAL = 41;
    int DOUBLERIGHTCURLY = 38;
    int error = 1;
    int LIGBEFORE = 35;
    int HRULE = 21;
    int LIGAFTER = 36;
    int UNKNOWN = 39;
    int ZONE = 42;
    int STARTHIEROGLYPHS = 17;
    int SENTENCEEND = 29;
    int LINEEND = 13;
    int ENDPHIL = 7;
    int COLON = 9;
    int BPAR = 8;
    int CLOSEBRACE = 31;
    int TABBINGCLEAR = 20;
    int SHADING = 23;
    int OPENBRACE = 30;
    int ENDCARTOUCHE = 5;
    int TEXT = 25;
    int BEGINPHIL = 6;
    int EPAR = 10;
    int IDENTIFIER = 40;
}
