package jsesh.hieroglyphs.graphics;

/**
 * HieroglyphicFontManager associates glyphs with codes. Test version
 * only. The real one will be an interface, and the real
 * implementation will take the glyphs from a database (or maybe for
 * usual ones from files, but this should be quite hidden).
 *
 *
 * Created: Mon Jun 10 17:59:58 2002
 *
 * @author <a href="mailto:rosmord@djedefhor.iut.univ-paris8.fr">Serge ROSMORDUC</a>
 */

import jsesh.hieroglyphs.graphics.HieroglyphicFontManager;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Set;

import jsesh.graphics.glyphs.bzr.BzrFontReader;
import jsesh.graphics.glyphs.bzr.simple.BzrSimpleFont;
import jsesh.graphics.glyphs.bzr.simple.BzrSimpleFontBuilder;

/**
 * The old fonts used by JSesh and tksesh.
 * @author rosmord
 *
 */
public class MemoryHieroglyphicFontManager implements HieroglyphicFontManager {

	static MemoryHieroglyphicFontManager instance = null;

	HashMap codes;
	BzrSimpleFont fonts[];
	boolean hasNewSigns= false;

	public MemoryHieroglyphicFontManager() {
		String fontNames[] =
			{
				"A.bzr",
				"B.bzr",
				"C.bzr",
				"D.bzr",
				"E.bzr",
				"F.bzr",
				"G.bzr",
				"H.bzr",
				"I.bzr",
				null,
				"K.bzr",
				"L.bzr",
				"M.bzr",
				"N.bzr",
				"O.bzr",
				"P.bzr",
				"Q.bzr",
				"R.bzr",
				"S.bzr",
				"T.bzr",
				"U.bzr",
				"V.bzr",
				"W.bzr",
				"X.bzr",
				"Y.bzr",
				"Z.bzr",
				"Aa.bzr" };
		fonts = new BzrSimpleFont[fontNames.length];

		BzrSimpleFontBuilder builder = new BzrSimpleFontBuilder();

		BzrFontReader reader = new BzrFontReader(builder);

		for (int i = 0; i < fonts.length; i++)
			try {
				if (fontNames[i] != null) {
					String rbase = "/jseshResources/goodbzr/";
					InputStream f =
						getClass().getResourceAsStream(rbase + fontNames[i]);
					//    ClassLoader.getSystemClassLoader().getResourceAsStream(rbase + fontNames[i]);    
					reader.read(f);
					fonts[i] = builder.getFont();
					// f.close(); Where should I put close ????
				}
			} catch (Exception e) {
				e.printStackTrace();
			}

		codes = new HashMap();
		// Now fill the map. ugly code !
		set("A", fonts['G' - 'A'].getChar(1 + 31));
		//set("i", fonts['M' - 'A'].getChar(17 + 31));
		//set("a", fonts['D' - 'A'].getChar(38 + 31));
		set("A3", fonts['A' - 'A'].getChar(3 + 31));
		//set("w", fonts['G' - 'A'].getChar(46 + 31));
		//set("W", fonts['Z' - 'A'].getChar(9 + 31));
		//set("b", fonts['D' - 'A'].getChar(61 + 31));
		//set("p", fonts['Q' - 'A'].getChar(3 + 31));
		//set("f", fonts['I' - 'A'].getChar(10 + 31));
		//set("m", fonts['G' - 'A'].getChar(19 + 31));
//		set("M", fonts[26].getChar(12 + 31));
//		set("n", fonts['N' - 'A'].getChar(35 + 31));
//		set("N", fonts['S' - 'A'].getChar(3 + 31));
//		set("r", fonts['D' - 'A'].getChar(21 + 31));
//		set("h", fonts['O' - 'A'].getChar(4 + 31));
//		set("H", fonts['V' - 'A'].getChar(28 + 31));
//		set("x", fonts[26].getChar(1 + 31));
//		set("X", fonts['F' - 'A'].getChar(32 + 31));
//		set("z", fonts['O' - 'A'].getChar(34 + 31));
//		set("s", fonts['S' - 'A'].getChar(32 + 31));
//		set("S", fonts['N' - 'A'].getChar(38 + 31));
//		set("q", fonts['N' - 'A'].getChar(29 + 31));
//		set("k", fonts['V' - 'A'].getChar(31 + 31));
//		set("g", fonts['W' - 'A'].getChar(13 + 31));
//		set("t", fonts['X' - 'A'].getChar(1 + 31));
//		set("d", fonts['D' - 'A'].getChar(48 + 31));
//		set("D", fonts['I' - 'A'].getChar(11 + 31));
		set("A1", fonts['A' - 'A'].getChar(1 + 31));
		set("A2", fonts['A' - 'A'].getChar(2 + 31));
		set("A4", fonts['A' - 'A'].getChar(4 + 31));
		set("A5", fonts['A' - 'A'].getChar(5 + 31));
		set("A6", fonts['A' - 'A'].getChar(6 + 31));
		set("A7", fonts['A' - 'A'].getChar(7 + 31));
		set("A8", fonts['A' - 'A'].getChar(8 + 31));
		set("A9", fonts['A' - 'A'].getChar(9 + 31));
		set("A10", fonts['A' - 'A'].getChar(10 + 31));
		set("A11", fonts['A' - 'A'].getChar(11 + 31));
		set("A12", fonts['A' - 'A'].getChar(12 + 31));
//		set("mSa", fonts['A' - 'A'].getChar(12 + 31));
		set("A13", fonts['A' - 'A'].getChar(13 + 31));
		set("A14", fonts['A' - 'A'].getChar(14 + 31));
		set("A14A", fonts['A' - 'A'].getChar(15 + 31));
		set("A15", fonts['A' - 'A'].getChar(16 + 31));
//		set("xr", fonts['A' - 'A'].getChar(16 + 31));
		set("A16", fonts['A' - 'A'].getChar(17 + 31));
		set("A17", fonts['A' - 'A'].getChar(18 + 31));
		set("Xrd", fonts['A' - 'A'].getChar(18 + 31));
		set("A17A", fonts['A' - 'A'].getChar(19 + 31));
		set("A18", fonts['A' - 'A'].getChar(20 + 31));
		set("A19", fonts['A' - 'A'].getChar(21 + 31));
		set("A20", fonts['A' - 'A'].getChar(22 + 31));
		set("A21", fonts['A' - 'A'].getChar(23 + 31));
//		set("sr", fonts['A' - 'A'].getChar(23 + 31));
		set("A22", fonts['A' - 'A'].getChar(24 + 31));
		set("A23", fonts['A' - 'A'].getChar(25 + 31));
		set("A24", fonts['A' - 'A'].getChar(26 + 31));
		set("A25", fonts['A' - 'A'].getChar(27 + 31));
		set("A59", fonts['A' - 'A'].getChar(28 + 31));
		set("A26", fonts['A' - 'A'].getChar(29 + 31));
		set("A27", fonts['A' - 'A'].getChar(30 + 31));
		set("A28", fonts['A' - 'A'].getChar(31 + 31));
		set("A29", fonts['A' - 'A'].getChar(32 + 31));
		set("A30", fonts['A' - 'A'].getChar(33 + 31));
		set("A31", fonts['A' - 'A'].getChar(34 + 31));
		set("A32", fonts['A' - 'A'].getChar(35 + 31));
		set("A33", fonts['A' - 'A'].getChar(36 + 31));
//		set("mniw", fonts['A' - 'A'].getChar(36 + 31));
		set("A34", fonts['A' - 'A'].getChar(37 + 31));
		set("A35", fonts['A' - 'A'].getChar(38 + 31));
		set("A36", fonts['A' - 'A'].getChar(39 + 31));
		set("A37", fonts['A' - 'A'].getChar(40 + 31));
		set("A38", fonts['A' - 'A'].getChar(41 + 31));
		set("qiz", fonts['A' - 'A'].getChar(41 + 31));
		set("A39", fonts['A' - 'A'].getChar(42 + 31));
		set("A40", fonts['A' - 'A'].getChar(43 + 31));
		set("A41", fonts['A' - 'A'].getChar(44 + 31));
		set("A42", fonts['A' - 'A'].getChar(45 + 31));
		set("A43", fonts['A' - 'A'].getChar(46 + 31));
		set("A44", fonts['A' - 'A'].getChar(47 + 31));
		set("A45", fonts['A' - 'A'].getChar(48 + 31));
		set("A46", fonts['A' - 'A'].getChar(49 + 31));
		set("A47", fonts['A' - 'A'].getChar(50 + 31));
		set("iry", fonts['A' - 'A'].getChar(50 + 31));
		set("A48", fonts['A' - 'A'].getChar(51 + 31));
		set("A49", fonts['A' - 'A'].getChar(52 + 31));
		set("A50", fonts['A' - 'A'].getChar(53 + 31));
		set("Sps", fonts['A' - 'A'].getChar(53 + 31));
		set("A51", fonts['A' - 'A'].getChar(54 + 31));
		set("Spsi", fonts['A' - 'A'].getChar(54 + 31));
		set("A52", fonts['A' - 'A'].getChar(55 + 31));
		set("A53", fonts['A' - 'A'].getChar(56 + 31));
		set("A54", fonts['A' - 'A'].getChar(57 + 31));
		set("A55", fonts['A' - 'A'].getChar(58 + 31));
		set("B1", fonts['B' - 'A'].getChar(1 + 31));
		set("B2", fonts['B' - 'A'].getChar(2 + 31));
		set("B3", fonts['B' - 'A'].getChar(3 + 31));
		set("msi", fonts['B' - 'A'].getChar(3 + 31));
		set("B4", fonts['B' - 'A'].getChar(4 + 31));
		set("B5", fonts['B' - 'A'].getChar(5 + 31));
		set("B6", fonts['B' - 'A'].getChar(6 + 31));
		set("B7", fonts['B' - 'A'].getChar(7 + 31));
		set("C1", fonts['C' - 'A'].getChar(1 + 31));
		set("C2", fonts['C' - 'A'].getChar(2 + 31));
		set("C3", fonts['C' - 'A'].getChar(3 + 31));
		set("DHwty", fonts['C' - 'A'].getChar(3 + 31));
		set("C4", fonts['C' - 'A'].getChar(4 + 31));
		set("Xnmw", fonts['C' - 'A'].getChar(4 + 31));
		set("C5", fonts['C' - 'A'].getChar(5 + 31));
		set("C6", fonts['C' - 'A'].getChar(6 + 31));
		set("inpw", fonts['C' - 'A'].getChar(6 + 31));
		set("C7", fonts['C' - 'A'].getChar(7 + 31));
		set("stX", fonts['C' - 'A'].getChar(7 + 31));
		set("C8", fonts['C' - 'A'].getChar(8 + 31));
		set("mnw", fonts['C' - 'A'].getChar(8 + 31));
		set("C9", fonts['C' - 'A'].getChar(9 + 31));
		set("C10", fonts['C' - 'A'].getChar(10 + 31));
		set("mAat", fonts['C' - 'A'].getChar(10 + 31));
		set("C10A", fonts['C' - 'A'].getChar(18 + 31));
		set("C11", fonts['C' - 'A'].getChar(11 + 31));
		set("HH", fonts['C' - 'A'].getChar(11 + 31));
		set("C12", fonts['C' - 'A'].getChar(12 + 31));
		set("C17", fonts['C' - 'A'].getChar(13 + 31));
		set("C18", fonts['C' - 'A'].getChar(14 + 31));
		set("C19", fonts['C' - 'A'].getChar(15 + 31));
		set("C20", fonts['C' - 'A'].getChar(16 + 31));
		set("C98", fonts['C' - 'A'].getChar(17 + 31));
		set("D1", fonts['D' - 'A'].getChar(1 + 31));
		set("tp", fonts['D' - 'A'].getChar(1 + 31));
		set("D2", fonts['D' - 'A'].getChar(2 + 31));
		set("Hr", fonts['D' - 'A'].getChar(2 + 31));
		set("D3", fonts['D' - 'A'].getChar(3 + 31));
		set("Sny", fonts['D' - 'A'].getChar(3 + 31));
		set("D4", fonts['D' - 'A'].getChar(4 + 31));
		set("ir", fonts['D' - 'A'].getChar(4 + 31));
		set("D5", fonts['D' - 'A'].getChar(5 + 31));
		set("D6", fonts['D' - 'A'].getChar(6 + 31));
		set("D7", fonts['D' - 'A'].getChar(7 + 31));
		set("D8", fonts['D' - 'A'].getChar(8 + 31));
		set("D9", fonts['D' - 'A'].getChar(9 + 31));
		set("rmi", fonts['D' - 'A'].getChar(9 + 31));
		set("D10", fonts['D' - 'A'].getChar(10 + 31));
		set("wDAt", fonts['D' - 'A'].getChar(10 + 31));
		set("D11", fonts['D' - 'A'].getChar(11 + 31));
		set("D12", fonts['D' - 'A'].getChar(12 + 31));
		set("D13", fonts['D' - 'A'].getChar(13 + 31));
		set("D14", fonts['D' - 'A'].getChar(14 + 31));
		set("D15", fonts['D' - 'A'].getChar(15 + 31));
		set("D16", fonts['D' - 'A'].getChar(16 + 31));
		set("D17", fonts['D' - 'A'].getChar(17 + 31));
		set("D18", fonts['D' - 'A'].getChar(18 + 31));
		set("D19", fonts['D' - 'A'].getChar(19 + 31));
		set("fnD", fonts['D' - 'A'].getChar(19 + 31));
		set("D20", fonts['D' - 'A'].getChar(20 + 31));
		set("D21", fonts['D' - 'A'].getChar(21 + 31));
		set("rA", fonts['D' - 'A'].getChar(21 + 31));
		set("D22", fonts['D' - 'A'].getChar(22 + 31));
		set("D23", fonts['D' - 'A'].getChar(23 + 31));
		set("D24", fonts['D' - 'A'].getChar(24 + 31));
		set("spt", fonts['D' - 'A'].getChar(24 + 31));
		set("D25", fonts['D' - 'A'].getChar(25 + 31));
		set("spty", fonts['D' - 'A'].getChar(25 + 31));
		set("D26", fonts['D' - 'A'].getChar(26 + 31));
		set("D27", fonts['D' - 'A'].getChar(27 + 31));
		set("mnD", fonts['D' - 'A'].getChar(27 + 31));
		set("D27A", fonts['D' - 'A'].getChar(28 + 31));
		set("D28", fonts['D' - 'A'].getChar(29 + 31));
		set("kA", fonts['D' - 'A'].getChar(29 + 31));
		set("D29", fonts['D' - 'A'].getChar(30 + 31));
		set("D30", fonts['D' - 'A'].getChar(31 + 31));
		set("D31", fonts['D' - 'A'].getChar(32 + 31));
		set("D32", fonts['D' - 'A'].getChar(33 + 31));
		set("D33", fonts['D' - 'A'].getChar(34 + 31));
		set("D34", fonts['D' - 'A'].getChar(35 + 31));
		set("aHA", fonts['D' - 'A'].getChar(35 + 31));
		set("D34A", fonts['D' - 'A'].getChar(36 + 31));
		set("D35", fonts['D' - 'A'].getChar(37 + 31));
		set("D36", fonts['D' - 'A'].getChar(38 + 31));
		set("D37", fonts['D' - 'A'].getChar(39 + 31));
		set("D38", fonts['D' - 'A'].getChar(40 + 31));
		set("D39", fonts['D' - 'A'].getChar(41 + 31));
		set("D40", fonts['D' - 'A'].getChar(42 + 31));
		set("D41", fonts['D' - 'A'].getChar(43 + 31));
		set("D42", fonts['D' - 'A'].getChar(44 + 31));
		set("D43", fonts['D' - 'A'].getChar(45 + 31));
		set("D44", fonts['D' - 'A'].getChar(46 + 31));
		set("D45", fonts['D' - 'A'].getChar(47 + 31));
		set("Dsr", fonts['D' - 'A'].getChar(47 + 31));
		set("D46", fonts['D' - 'A'].getChar(48 + 31));
		set("D47", fonts['D' - 'A'].getChar(49 + 31));
		set("D46A", fonts['D' - 'A'].getChar(50 + 31));
		set("D48", fonts['D' - 'A'].getChar(51 + 31));
		set("D49", fonts['D' - 'A'].getChar(52 + 31));
		set("D50", fonts['D' - 'A'].getChar(53 + 31));
		set("Dba", fonts['D' - 'A'].getChar(53 + 31));
		set("D51", fonts['D' - 'A'].getChar(54 + 31));
		set("D52", fonts['D' - 'A'].getChar(55 + 31));
		set("mt", fonts['D' - 'A'].getChar(55 + 31));
		set("D53", fonts['D' - 'A'].getChar(56 + 31));
		set("D54", fonts['D' - 'A'].getChar(57 + 31));
		set("D55", fonts['D' - 'A'].getChar(58 + 31));
		set("D56", fonts['D' - 'A'].getChar(59 + 31));
		set("rd", fonts['D' - 'A'].getChar(59 + 31));
		set("sbq", fonts['D' - 'A'].getChar(59 + 31));
		set("gH", fonts['D' - 'A'].getChar(59 + 31));
		set("gHs", fonts['D' - 'A'].getChar(59 + 31));
		set("D57", fonts['D' - 'A'].getChar(60 + 31));
		set("D58", fonts['D' - 'A'].getChar(61 + 31));
		set("D59", fonts['D' - 'A'].getChar(62 + 31));
		set("ab", fonts['D' - 'A'].getChar(62 + 31));
		set("D60", fonts['D' - 'A'].getChar(63 + 31));
		set("wab", fonts['D' - 'A'].getChar(63 + 31));
		set("D61", fonts['D' - 'A'].getChar(64 + 31));
		set("sAH", fonts['D' - 'A'].getChar(64 + 31));
		set("D62", fonts['D' - 'A'].getChar(65 + 31));
		set("D63", fonts['D' - 'A'].getChar(66 + 31));
		set("E1", fonts['E' - 'A'].getChar(1 + 31));
		set("E2", fonts['E' - 'A'].getChar(2 + 31));
		set("E3", fonts['E' - 'A'].getChar(3 + 31));
		set("E4", fonts['E' - 'A'].getChar(4 + 31));
		set("E5", fonts['E' - 'A'].getChar(5 + 31));
		set("E6", fonts['E' - 'A'].getChar(6 + 31));
		set("zzmt", fonts['E' - 'A'].getChar(6 + 31));
		set("E7", fonts['E' - 'A'].getChar(7 + 31));
		set("E8", fonts['E' - 'A'].getChar(8 + 31));
		set("E8A", fonts['E' - 'A'].getChar(9 + 31));
		set("E9", fonts['E' - 'A'].getChar(10 + 31));
		set("E10", fonts['E' - 'A'].getChar(11 + 31));
		set("E11", fonts['E' - 'A'].getChar(12 + 31));
		set("E12", fonts['E' - 'A'].getChar(13 + 31));
		set("E13", fonts['E' - 'A'].getChar(14 + 31));
		set("E14", fonts['E' - 'A'].getChar(15 + 31));
		set("E15", fonts['E' - 'A'].getChar(16 + 31));
		set("E16", fonts['E' - 'A'].getChar(17 + 31));
		set("E17", fonts['E' - 'A'].getChar(18 + 31));
		set("zAb", fonts['E' - 'A'].getChar(18 + 31));
		set("E18", fonts['E' - 'A'].getChar(19 + 31));
		set("E19", fonts['E' - 'A'].getChar(20 + 31));
		set("E20", fonts['E' - 'A'].getChar(21 + 31));
		set("E21", fonts['E' - 'A'].getChar(22 + 31));
		set("E22", fonts['E' - 'A'].getChar(23 + 31));
		set("mAi", fonts['E' - 'A'].getChar(23 + 31));
		set("E23", fonts['E' - 'A'].getChar(24 + 31));
		set("rw", fonts['E' - 'A'].getChar(24 + 31));
		set("l", fonts['E' - 'A'].getChar(24 + 31));
		set("E24", fonts['E' - 'A'].getChar(25 + 31));
		set("Aby", fonts['E' - 'A'].getChar(25 + 31));
		set("E25", fonts['E' - 'A'].getChar(26 + 31));
		set("E26", fonts['E' - 'A'].getChar(27 + 31));
		set("E27", fonts['E' - 'A'].getChar(28 + 31));
		set("E28", fonts['E' - 'A'].getChar(29 + 31));
		set("E29", fonts['E' - 'A'].getChar(30 + 31));
		set("E30", fonts['E' - 'A'].getChar(31 + 31));
		set("E31", fonts['E' - 'A'].getChar(32 + 31));
		set("E32", fonts['E' - 'A'].getChar(33 + 31));
		set("E33", fonts['E' - 'A'].getChar(34 + 31));
		set("E34", fonts['E' - 'A'].getChar(35 + 31));
		set("wn", fonts['E' - 'A'].getChar(35 + 31));
		set("F1", fonts['F' - 'A'].getChar(1 + 31));
		set("F2", fonts['F' - 'A'].getChar(2 + 31));
		set("F3", fonts['F' - 'A'].getChar(3 + 31));
		set("F4", fonts['F' - 'A'].getChar(4 + 31));
		set("HAt", fonts['F' - 'A'].getChar(4 + 31));
		set("F5", fonts['F' - 'A'].getChar(5 + 31));
		set("SsA", fonts['F' - 'A'].getChar(5 + 31));
		set("F6", fonts['F' - 'A'].getChar(6 + 31));
		set("F7", fonts['F' - 'A'].getChar(7 + 31));
		set("F8", fonts['F' - 'A'].getChar(8 + 31));
		set("F9", fonts['F' - 'A'].getChar(9 + 31));
		set("F10", fonts['F' - 'A'].getChar(10 + 31));
		set("F11", fonts['F' - 'A'].getChar(11 + 31));
		set("F12", fonts['F' - 'A'].getChar(12 + 31));
		set("wsr", fonts['F' - 'A'].getChar(12 + 31));
		set("F13", fonts['F' - 'A'].getChar(13 + 31));
		set("wp", fonts['F' - 'A'].getChar(13 + 31));
		set("F14", fonts['F' - 'A'].getChar(14 + 31));
		set("F15", fonts['F' - 'A'].getChar(15 + 31));
		set("F16", fonts['F' - 'A'].getChar(16 + 31));
		set("db", fonts['F' - 'A'].getChar(16 + 31));
		set("F17", fonts['F' - 'A'].getChar(17 + 31));
		set("F18", fonts['F' - 'A'].getChar(18 + 31));
		set("Hw", fonts['F' - 'A'].getChar(18 + 31));
		set("bH", fonts['F' - 'A'].getChar(18 + 31));
		set("F19", fonts['F' - 'A'].getChar(19 + 31));
		set("F20", fonts['F' - 'A'].getChar(20 + 31));
		set("ns", fonts['F' - 'A'].getChar(20 + 31));
		set("F21", fonts['F' - 'A'].getChar(21 + 31));
		set("idn", fonts['F' - 'A'].getChar(21 + 31));
		set("msDr", fonts['F' - 'A'].getChar(21 + 31));
		set("sDm", fonts['F' - 'A'].getChar(21 + 31));
		set("DrD", fonts['F' - 'A'].getChar(21 + 31));
		set("F22", fonts['F' - 'A'].getChar(22 + 31));
		set("pH", fonts['F' - 'A'].getChar(22 + 31));
		set("kfA", fonts['F' - 'A'].getChar(22 + 31));
		set("F23", fonts['F' - 'A'].getChar(23 + 31));
		set("xpS", fonts['F' - 'A'].getChar(23 + 31));
		set("F24", fonts['F' - 'A'].getChar(24 + 31));
		set("F25", fonts['F' - 'A'].getChar(25 + 31));
		set("wHm", fonts['F' - 'A'].getChar(25 + 31));
		set("F26", fonts['F' - 'A'].getChar(26 + 31));
		set("Xn", fonts['F' - 'A'].getChar(26 + 31));
		set("F27", fonts['F' - 'A'].getChar(27 + 31));
		set("F28", fonts['F' - 'A'].getChar(28 + 31));
		set("F29", fonts['F' - 'A'].getChar(29 + 31));
		set("sti", fonts['F' - 'A'].getChar(29 + 31));
		set("F30", fonts['F' - 'A'].getChar(30 + 31));
		set("Sd", fonts['F' - 'A'].getChar(30 + 31));
		set("F31", fonts['F' - 'A'].getChar(31 + 31));
		set("ms", fonts['F' - 'A'].getChar(31 + 31));
		set("F32", fonts['F' - 'A'].getChar(32 + 31));
		set("F33", fonts['F' - 'A'].getChar(33 + 31));
		set("sd", fonts['F' - 'A'].getChar(33 + 31));
		set("F34", fonts['F' - 'A'].getChar(34 + 31));
		set("ib", fonts['F' - 'A'].getChar(34 + 31));
		set("F35", fonts['F' - 'A'].getChar(35 + 31));
		set("nfr", fonts['F' - 'A'].getChar(35 + 31));
		set("F36", fonts['F' - 'A'].getChar(36 + 31));
		set("zmA", fonts['F' - 'A'].getChar(36 + 31));
		set("F37", fonts['F' - 'A'].getChar(37 + 31));
		set("F38", fonts['F' - 'A'].getChar(38 + 31));
		set("F39", fonts['F' - 'A'].getChar(39 + 31));
		set("imAx", fonts['F' - 'A'].getChar(39 + 31));
		set("F40", fonts['F' - 'A'].getChar(40 + 31));
		set("Aw", fonts['F' - 'A'].getChar(40 + 31));
		set("F41", fonts['F' - 'A'].getChar(41 + 31));
		set("F42", fonts['F' - 'A'].getChar(42 + 31));
		set("spr", fonts['F' - 'A'].getChar(42 + 31));
		set("F43", fonts['F' - 'A'].getChar(43 + 31));
		set("F44", fonts['F' - 'A'].getChar(44 + 31));
		set("iwa", fonts['F' - 'A'].getChar(44 + 31));
		set("isw", fonts['F' - 'A'].getChar(44 + 31));
		set("F45", fonts['F' - 'A'].getChar(45 + 31));
		set("F46", fonts['F' - 'A'].getChar(46 + 31));
		set("pXr", fonts['F' - 'A'].getChar(46 + 31));
		set("qAb", fonts['F' - 'A'].getChar(46 + 31));
		set("F47", fonts['F' - 'A'].getChar(47 + 31));
		set("F48", fonts['F' - 'A'].getChar(48 + 31));
		set("F49", fonts['F' - 'A'].getChar(49 + 31));
		set("F50", fonts['F' - 'A'].getChar(50 + 31));
		set("F51", fonts['F' - 'A'].getChar(51 + 31));
		set("F52", fonts['F' - 'A'].getChar(52 + 31));
		set("F37B", fonts['F' - 'A'].getChar(53 + 31));
		set("G1", fonts['G' - 'A'].getChar(1 + 31));
		set("G2", fonts['G' - 'A'].getChar(2 + 31));
		set("AA", fonts['G' - 'A'].getChar(2 + 31));
		set("G3", fonts['G' - 'A'].getChar(3 + 31));
		set("G4", fonts['G' - 'A'].getChar(4 + 31));
		set("tyw", fonts['G' - 'A'].getChar(4 + 31));
		set("G5", fonts['G' - 'A'].getChar(5 + 31));
		set("G6", fonts['G' - 'A'].getChar(6 + 31));
		set("G7", fonts['G' - 'A'].getChar(7 + 31));
		set("G7A", fonts['G' - 'A'].getChar(8 + 31));
		set("G7B", fonts['G' - 'A'].getChar(9 + 31));
		set("G8", fonts['G' - 'A'].getChar(10 + 31));
		set("G9", fonts['G' - 'A'].getChar(11 + 31));
		set("G10", fonts['G' - 'A'].getChar(12 + 31));
		set("G11", fonts['G' - 'A'].getChar(13 + 31));
		set("G12", fonts['G' - 'A'].getChar(14 + 31));
		set("G13", fonts['G' - 'A'].getChar(15 + 31));
		set("G14", fonts['G' - 'A'].getChar(16 + 31));
		set("mwt", fonts['G' - 'A'].getChar(16 + 31));
		set("G15", fonts['G' - 'A'].getChar(17 + 31));
		set("G16", fonts['G' - 'A'].getChar(18 + 31));
		set("nbty", fonts['G' - 'A'].getChar(18 + 31));
		set("G17", fonts['G' - 'A'].getChar(19 + 31));
		set("G18", fonts['G' - 'A'].getChar(20 + 31));
		set("mm", fonts['G' - 'A'].getChar(20 + 31));
		set("G19", fonts['G' - 'A'].getChar(21 + 31));
		set("G20", fonts['G' - 'A'].getChar(22 + 31));
		set("G21", fonts['G' - 'A'].getChar(23 + 31));
		set("nH", fonts['G' - 'A'].getChar(23 + 31));
		set("G22", fonts['G' - 'A'].getChar(24 + 31));
		set("Db", fonts['G' - 'A'].getChar(24 + 31));
		set("G23", fonts['G' - 'A'].getChar(25 + 31));
		set("rxyt", fonts['G' - 'A'].getChar(25 + 31));
		set("G24", fonts['G' - 'A'].getChar(26 + 31));
		set("G25", fonts['G' - 'A'].getChar(27 + 31));
		set("Ax", fonts['G' - 'A'].getChar(27 + 31));
		set("G26", fonts['G' - 'A'].getChar(28 + 31));
		set("G26A", fonts['G' - 'A'].getChar(29 + 31));
		set("G27", fonts['G' - 'A'].getChar(30 + 31));
		set("dSr", fonts['G' - 'A'].getChar(30 + 31));
		set("G28", fonts['G' - 'A'].getChar(31 + 31));
		set("gm", fonts['G' - 'A'].getChar(31 + 31));
		set("G29", fonts['G' - 'A'].getChar(32 + 31));
		set("bA", fonts['G' - 'A'].getChar(32 + 31));
		set("G30", fonts['G' - 'A'].getChar(33 + 31));
		set("G31", fonts['G' - 'A'].getChar(34 + 31));
		set("G32", fonts['G' - 'A'].getChar(35 + 31));
		set("baHi", fonts['G' - 'A'].getChar(35 + 31));
		set("G33", fonts['G' - 'A'].getChar(36 + 31));
		set("G34", fonts['G' - 'A'].getChar(37 + 31));
		set("G35", fonts['G' - 'A'].getChar(38 + 31));
		set("aq", fonts['G' - 'A'].getChar(38 + 31));
		set("G36", fonts['G' - 'A'].getChar(39 + 31));
		set("wr", fonts['G' - 'A'].getChar(39 + 31));
		set("G37", fonts['G' - 'A'].getChar(40 + 31));
		set("G38", fonts['G' - 'A'].getChar(41 + 31));
		set("gb", fonts['G' - 'A'].getChar(41 + 31));
		set("G39", fonts['G' - 'A'].getChar(42 + 31));
		set("zA", fonts['G' - 'A'].getChar(42 + 31));
		set("G40", fonts['G' - 'A'].getChar(43 + 31));
		set("pA", fonts['G' - 'A'].getChar(43 + 31));
		set("G41", fonts['G' - 'A'].getChar(44 + 31));
		set("xn", fonts['G' - 'A'].getChar(44 + 31));
		set("G42", fonts['G' - 'A'].getChar(45 + 31));
		set("wSA", fonts['G' - 'A'].getChar(45 + 31));
		set("G43", fonts['G' - 'A'].getChar(46 + 31));
		set("G44", fonts['G' - 'A'].getChar(47 + 31));
		set("ww", fonts['G' - 'A'].getChar(47 + 31));
		set("G45", fonts['G' - 'A'].getChar(48 + 31));
		set("G46", fonts['G' - 'A'].getChar(49 + 31));
		set("mAw", fonts['G' - 'A'].getChar(49 + 31));
		set("G47", fonts['G' - 'A'].getChar(50 + 31));
		set("TA", fonts['G' - 'A'].getChar(50 + 31));
		set("G48", fonts['G' - 'A'].getChar(51 + 31));
		set("G49", fonts['G' - 'A'].getChar(52 + 31));
		set("G50", fonts['G' - 'A'].getChar(53 + 31));
		set("G51", fonts['G' - 'A'].getChar(54 + 31));
		set("G52", fonts['G' - 'A'].getChar(55 + 31));
		set("G53", fonts['G' - 'A'].getChar(56 + 31));
		set("G54", fonts['G' - 'A'].getChar(57 + 31));
		set("snD", fonts['G' - 'A'].getChar(57 + 31));
		set("H1", fonts['H' - 'A'].getChar(1 + 31));
		set("H2", fonts['H' - 'A'].getChar(2 + 31));
		set("wSm", fonts['H' - 'A'].getChar(2 + 31));
		set("H3", fonts['H' - 'A'].getChar(3 + 31));
		set("pAq", fonts['H' - 'A'].getChar(3 + 31));
		set("H4", fonts['H' - 'A'].getChar(4 + 31));
		set("H5", fonts['H' - 'A'].getChar(5 + 31));
		set("H6", fonts['H' - 'A'].getChar(6 + 31));
		set("Sw", fonts['H' - 'A'].getChar(6 + 31));
		set("H6A", fonts['H' - 'A'].getChar(7 + 31));
		set("H7", fonts['H' - 'A'].getChar(8 + 31));
		set("H8", fonts['H' - 'A'].getChar(9 + 31));
		set("I1", fonts['I' - 'A'].getChar(1 + 31));
		set("aSA", fonts['I' - 'A'].getChar(1 + 31));
		set("I2", fonts['I' - 'A'].getChar(2 + 31));
		set("Styw", fonts['I' - 'A'].getChar(2 + 31));
		set("I3", fonts['I' - 'A'].getChar(3 + 31));
		set("mzH", fonts['I' - 'A'].getChar(3 + 31));
		set("I5A", fonts['I' - 'A'].getChar(4 + 31));
		set("I4", fonts['I' - 'A'].getChar(5 + 31));
		set("sbk", fonts['I' - 'A'].getChar(5 + 31));
		set("I5", fonts['I' - 'A'].getChar(6 + 31));
		set("sAq", fonts['I' - 'A'].getChar(6 + 31));
		set("I6", fonts['I' - 'A'].getChar(7 + 31));
		set("km", fonts['I' - 'A'].getChar(7 + 31));
		set("I7", fonts['I' - 'A'].getChar(8 + 31));
		set("I8", fonts['I' - 'A'].getChar(9 + 31));
		set("Hfn", fonts['I' - 'A'].getChar(9 + 31));
		set("I9", fonts['I' - 'A'].getChar(10 + 31));
		set("I10", fonts['I' - 'A'].getChar(11 + 31));
		set("I11", fonts['I' - 'A'].getChar(12 + 31));
		set("DD", fonts['I' - 'A'].getChar(12 + 31));
		set("I12", fonts['I' - 'A'].getChar(13 + 31));
		set("I13", fonts['I' - 'A'].getChar(14 + 31));
		set("I14", fonts['I' - 'A'].getChar(15 + 31));
		set("I15", fonts['I' - 'A'].getChar(16 + 31));
		set("K1", fonts['K' - 'A'].getChar(1 + 31));
		set("in", fonts['K' - 'A'].getChar(1 + 31));
		set("K2", fonts['K' - 'A'].getChar(2 + 31));
		set("K3", fonts['K' - 'A'].getChar(3 + 31));
		set("ad", fonts['K' - 'A'].getChar(3 + 31));
		set("K4", fonts['K' - 'A'].getChar(4 + 31));
		set("XA", fonts['K' - 'A'].getChar(4 + 31));
		set("K5", fonts['K' - 'A'].getChar(5 + 31));
		set("bz", fonts['K' - 'A'].getChar(5 + 31));
		set("K7", fonts['K' - 'A'].getChar(6 + 31));
		set("K6", fonts['K' - 'A'].getChar(7 + 31));
		set("nSmt", fonts['K' - 'A'].getChar(7 + 31));
		set("L1", fonts['L' - 'A'].getChar(1 + 31));
		set("xpr", fonts['L' - 'A'].getChar(1 + 31));
		set("L2", fonts['L' - 'A'].getChar(2 + 31));
		set("bit", fonts['L' - 'A'].getChar(2 + 31));
		set("L3", fonts['L' - 'A'].getChar(3 + 31));
		set("L4", fonts['L' - 'A'].getChar(4 + 31));
		set("L5", fonts['L' - 'A'].getChar(5 + 31));
		set("L6", fonts['L' - 'A'].getChar(6 + 31));
		set("L7", fonts['L' - 'A'].getChar(7 + 31));
		set("srqt", fonts['L' - 'A'].getChar(7 + 31));
		set("M1", fonts['M' - 'A'].getChar(1 + 31));
		set("iAm", fonts['M' - 'A'].getChar(1 + 31));
		set("M2", fonts['M' - 'A'].getChar(2 + 31));
		set("Hn", fonts['M' - 'A'].getChar(2 + 31));
		set("M3", fonts['M' - 'A'].getChar(3 + 31));
		set("xt", fonts['M' - 'A'].getChar(3 + 31));
		set("M4", fonts['M' - 'A'].getChar(4 + 31));
		set("rnp", fonts['M' - 'A'].getChar(4 + 31));
		set("M5", fonts['M' - 'A'].getChar(5 + 31));
		set("M6", fonts['M' - 'A'].getChar(6 + 31));
		set("tr", fonts['M' - 'A'].getChar(6 + 31));
		set("M7", fonts['M' - 'A'].getChar(7 + 31));
		set("M8", fonts['M' - 'A'].getChar(8 + 31));
		set("SA", fonts['M' - 'A'].getChar(8 + 31));
		set("M9", fonts['M' - 'A'].getChar(9 + 31));
		set("zSn", fonts['M' - 'A'].getChar(9 + 31));
		set("M10", fonts['M' - 'A'].getChar(10 + 31));
		set("M11", fonts['M' - 'A'].getChar(11 + 31));
		set("wdn", fonts['M' - 'A'].getChar(11 + 31));
		set("M12", fonts['M' - 'A'].getChar(12 + 31));
		set("xA", fonts['M' - 'A'].getChar(12 + 31));
		set("M13", fonts['M' - 'A'].getChar(13 + 31));
		set("wAD", fonts['M' - 'A'].getChar(13 + 31));
		set("M14", fonts['M' - 'A'].getChar(14 + 31));
		set("M15", fonts['M' - 'A'].getChar(15 + 31));
		set("M16", fonts['M' - 'A'].getChar(16 + 31));
		set("HA", fonts['M' - 'A'].getChar(16 + 31));
		set("M17", fonts['M' - 'A'].getChar(17 + 31));
		set("M18", fonts['M' - 'A'].getChar(18 + 31));
		set("ii", fonts['M' - 'A'].getChar(18 + 31));
		set("M19", fonts['M' - 'A'].getChar(19 + 31));
		set("M20", fonts['M' - 'A'].getChar(20 + 31));
		set("sxt", fonts['M' - 'A'].getChar(20 + 31));
		set("M21", fonts['M' - 'A'].getChar(21 + 31));
		set("sm", fonts['M' - 'A'].getChar(21 + 31));
		set("M22", fonts['M' - 'A'].getChar(22 + 31));
		set("M23", fonts['M' - 'A'].getChar(23 + 31));
		set("sw", fonts['M' - 'A'].getChar(23 + 31));
		set("M24", fonts['M' - 'A'].getChar(24 + 31));
		set("rsw", fonts['M' - 'A'].getChar(24 + 31));
		set("M25", fonts['M' - 'A'].getChar(25 + 31));
		set("M26", fonts['M' - 'A'].getChar(26 + 31));
		set("Sma", fonts['M' - 'A'].getChar(26 + 31));
		set("M27", fonts['M' - 'A'].getChar(27 + 31));
		set("M28", fonts['M' - 'A'].getChar(28 + 31));
		set("M29", fonts['M' - 'A'].getChar(29 + 31));
		set("nDm", fonts['M' - 'A'].getChar(29 + 31));
		set("M30", fonts['M' - 'A'].getChar(30 + 31));
		set("bnr", fonts['M' - 'A'].getChar(30 + 31));
		set("M31", fonts['M' - 'A'].getChar(31 + 31));
		set("M32", fonts['M' - 'A'].getChar(32 + 31));
		set("M33", fonts['M' - 'A'].getChar(33 + 31));
		set("M34", fonts['M' - 'A'].getChar(34 + 31));
		set("bdt", fonts['M' - 'A'].getChar(34 + 31));
		set("M35", fonts['M' - 'A'].getChar(35 + 31));
		set("M36", fonts['M' - 'A'].getChar(36 + 31));
		set("Dr", fonts['M' - 'A'].getChar(36 + 31));
		set("M37", fonts['M' - 'A'].getChar(37 + 31));
		set("M38", fonts['M' - 'A'].getChar(38 + 31));
		set("M39", fonts['M' - 'A'].getChar(39 + 31));
		set("M40", fonts['M' - 'A'].getChar(40 + 31));
		set("iz", fonts['M' - 'A'].getChar(40 + 31));
		set("M41", fonts['M' - 'A'].getChar(41 + 31));
		set("M42", fonts['M' - 'A'].getChar(42 + 31));
		set("M43", fonts['M' - 'A'].getChar(43 + 31));
		set("M44", fonts['M' - 'A'].getChar(44 + 31));
		set("N1", fonts['N' - 'A'].getChar(1 + 31));
		set("pt", fonts['N' - 'A'].getChar(1 + 31));
		set("N2", fonts['N' - 'A'].getChar(2 + 31));
		set("N3", fonts['N' - 'A'].getChar(3 + 31));
		set("N4", fonts['N' - 'A'].getChar(4 + 31));
		set("iAdt", fonts['N' - 'A'].getChar(4 + 31));
		set("idt", fonts['N' - 'A'].getChar(4 + 31));
		set("N5", fonts['N' - 'A'].getChar(5 + 31));
		set("ra", fonts['N' - 'A'].getChar(5 + 31));
		set("zw", fonts['N' - 'A'].getChar(5 + 31));
		set("hrw", fonts['N' - 'A'].getChar(5 + 31));
		set("N6", fonts['N' - 'A'].getChar(6 + 31));
		set("N7", fonts['N' - 'A'].getChar(7 + 31));
		set("N8", fonts['N' - 'A'].getChar(8 + 31));
		set("Hnmmt", fonts['N' - 'A'].getChar(8 + 31));
		set("N9", fonts['N' - 'A'].getChar(9 + 31));
		set("pzD", fonts['N' - 'A'].getChar(9 + 31));
		set("N10", fonts['N' - 'A'].getChar(10 + 31));
		set("N11", fonts['N' - 'A'].getChar(11 + 31));
		set("Abd", fonts['N' - 'A'].getChar(11 + 31));
		set("iaH", fonts['N' - 'A'].getChar(11 + 31));
		set("N12", fonts['N' - 'A'].getChar(12 + 31));
		set("N13", fonts['N' - 'A'].getChar(13 + 31));
		set("N14", fonts['N' - 'A'].getChar(14 + 31));
		set("dwA", fonts['N' - 'A'].getChar(14 + 31));
		set("sbA", fonts['N' - 'A'].getChar(14 + 31));
		set("N15", fonts['N' - 'A'].getChar(15 + 31));
		set("dwAt", fonts['N' - 'A'].getChar(15 + 31));
		set("N16", fonts['N' - 'A'].getChar(16 + 31));
		set("tA", fonts['N' - 'A'].getChar(16 + 31));
		set("N17", fonts['N' - 'A'].getChar(17 + 31));
		set("N18", fonts['N' - 'A'].getChar(18 + 31));
		set("iw", fonts['N' - 'A'].getChar(18 + 31));
		set("N19", fonts['N' - 'A'].getChar(19 + 31));
		set("N20", fonts['N' - 'A'].getChar(20 + 31));
		set("wDb", fonts['N' - 'A'].getChar(20 + 31));
		set("N21", fonts['N' - 'A'].getChar(21 + 31));
		set("N22", fonts['N' - 'A'].getChar(22 + 31));
		set("N23", fonts['N' - 'A'].getChar(23 + 31));
		set("N24", fonts['N' - 'A'].getChar(24 + 31));
		set("spAt", fonts['N' - 'A'].getChar(24 + 31));
		set("N25", fonts['N' - 'A'].getChar(25 + 31));
		set("xAst", fonts['N' - 'A'].getChar(25 + 31));
		set("N26", fonts['N' - 'A'].getChar(26 + 31));
		set("Dw", fonts['N' - 'A'].getChar(26 + 31));
		set("N27", fonts['N' - 'A'].getChar(27 + 31));
		set("Axt", fonts['N' - 'A'].getChar(27 + 31));
		set("N28", fonts['N' - 'A'].getChar(28 + 31));
		set("xa", fonts['N' - 'A'].getChar(28 + 31));
		set("N29", fonts['N' - 'A'].getChar(29 + 31));
		set("N30", fonts['N' - 'A'].getChar(30 + 31));
		set("iAt", fonts['N' - 'A'].getChar(30 + 31));
		set("N31", fonts['N' - 'A'].getChar(31 + 31));
		set("N32", fonts['N' - 'A'].getChar(32 + 31));
		set("N33", fonts['N' - 'A'].getChar(33 + 31));
		set("N34", fonts['N' - 'A'].getChar(34 + 31));
		set("N35", fonts['N' - 'A'].getChar(35 + 31));
		set("N35A", fonts['N' - 'A'].getChar(36 + 31));
		set("mw", fonts['N' - 'A'].getChar(36 + 31));
		set("N36", fonts['N' - 'A'].getChar(37 + 31));
		set("N37", fonts['N' - 'A'].getChar(38 + 31));
		set("N38", fonts['N' - 'A'].getChar(39 + 31));
		set("N39", fonts['N' - 'A'].getChar(40 + 31));
		set("N40", fonts['N' - 'A'].getChar(41 + 31));
		set("Sm", fonts['N' - 'A'].getChar(41 + 31));
		set("N41", fonts['N' - 'A'].getChar(42 + 31));
		set("id", fonts['N' - 'A'].getChar(42 + 31));
		set("N42", fonts['N' - 'A'].getChar(42 + 31));
		set("O1", fonts['O' - 'A'].getChar(1 + 31));
		set("pr", fonts['O' - 'A'].getChar(1 + 31));
		set("O2", fonts['O' - 'A'].getChar(2 + 31));
		set("O3", fonts['O' - 'A'].getChar(3 + 31));
		set("O4", fonts['O' - 'A'].getChar(4 + 31));
		set("O5", fonts['O' - 'A'].getChar(5 + 31));
		set("O6", fonts['O' - 'A'].getChar(6 + 31));
		set("Hwt", fonts['O' - 'A'].getChar(6 + 31));
		set("O7", fonts['O' - 'A'].getChar(7 + 31));
		set("O8", fonts['O' - 'A'].getChar(8 + 31));
		set("O9", fonts['O' - 'A'].getChar(9 + 31));
		set("O10", fonts['O' - 'A'].getChar(10 + 31));
		set("O11", fonts['O' - 'A'].getChar(11 + 31));
		set("aH", fonts['O' - 'A'].getChar(11 + 31));
		set("O12", fonts['O' - 'A'].getChar(12 + 31));
		set("O13", fonts['O' - 'A'].getChar(13 + 31));
		set("O14", fonts['O' - 'A'].getChar(14 + 31));
		set("O15", fonts['O' - 'A'].getChar(15 + 31));
		set("wsxt", fonts['O' - 'A'].getChar(15 + 31));
		set("O16", fonts['O' - 'A'].getChar(16 + 31));
		set("O17", fonts['O' - 'A'].getChar(17 + 31));
		set("O18", fonts['O' - 'A'].getChar(18 + 31));
		set("kAr", fonts['O' - 'A'].getChar(18 + 31));
		set("O19", fonts['O' - 'A'].getChar(19 + 31));
		set("O20", fonts['O' - 'A'].getChar(20 + 31));
		set("O21", fonts['O' - 'A'].getChar(21 + 31));
		set("O22", fonts['O' - 'A'].getChar(22 + 31));
		set("zH", fonts['O' - 'A'].getChar(22 + 31));
		set("O23", fonts['O' - 'A'].getChar(23 + 31));
		set("O24", fonts['O' - 'A'].getChar(24 + 31));
		set("O25", fonts['O' - 'A'].getChar(25 + 31));
		set("txn", fonts['O' - 'A'].getChar(25 + 31));
		set("O26", fonts['O' - 'A'].getChar(26 + 31));
		set("O27", fonts['O' - 'A'].getChar(27 + 31));
		set("O28", fonts['O' - 'A'].getChar(28 + 31));
		set("iwn", fonts['O' - 'A'].getChar(28 + 31));
		set("O29", fonts['O' - 'A'].getChar(29 + 31));
		set("aA", fonts['O' - 'A'].getChar(29 + 31));
		set("aAv", fonts['O' - 'A'].getChar(52 + 31));
		set("O29v", fonts['O' - 'A'].getChar(52 + 31));
		set("O30", fonts['O' - 'A'].getChar(30 + 31));
		set("zxnt", fonts['O' - 'A'].getChar(30 + 31));
		set("O31", fonts['O' - 'A'].getChar(31 + 31));
		set("O32", fonts['O' - 'A'].getChar(32 + 31));
		set("O33", fonts['O' - 'A'].getChar(33 + 31));
		set("O34", fonts['O' - 'A'].getChar(34 + 31));
		set("O35", fonts['O' - 'A'].getChar(35 + 31));
		set("zb", fonts['O' - 'A'].getChar(35 + 31));
		set("O36", fonts['O' - 'A'].getChar(36 + 31));
		set("inb", fonts['O' - 'A'].getChar(36 + 31));
		set("O37", fonts['O' - 'A'].getChar(37 + 31));
		set("O38", fonts['O' - 'A'].getChar(38 + 31));
		set("O39", fonts['O' - 'A'].getChar(39 + 31));
		set("O40", fonts['O' - 'A'].getChar(40 + 31));
		set("O41", fonts['O' - 'A'].getChar(41 + 31));
		set("O42", fonts['O' - 'A'].getChar(42 + 31));
		set("Szp", fonts['O' - 'A'].getChar(42 + 31));
		set("O43", fonts['O' - 'A'].getChar(43 + 31));
		set("O44", fonts['O' - 'A'].getChar(44 + 31));
		set("O45", fonts['O' - 'A'].getChar(45 + 31));
		set("ipt", fonts['O' - 'A'].getChar(45 + 31));
		set("O46", fonts['O' - 'A'].getChar(46 + 31));
		set("O47", fonts['O' - 'A'].getChar(47 + 31));
		set("nxn", fonts['O' - 'A'].getChar(47 + 31));
		set("O48", fonts['O' - 'A'].getChar(48 + 31));
		set("O49", fonts['O' - 'A'].getChar(49 + 31));
		set("niwt", fonts['O' - 'A'].getChar(49 + 31));
		set("O50", fonts['O' - 'A'].getChar(50 + 31));
		set("zp", fonts['O' - 'A'].getChar(50 + 31));
		set("O51", fonts['O' - 'A'].getChar(51 + 31));
		set("Snwt", fonts['O' - 'A'].getChar(51 + 31));
		set("P1", fonts['P' - 'A'].getChar(1 + 31));
		set("P1A", fonts['P' - 'A'].getChar(2 + 31));
		set("P2", fonts['P' - 'A'].getChar(3 + 31));
		set("P3", fonts['P' - 'A'].getChar(4 + 31));
		set("P4", fonts['P' - 'A'].getChar(5 + 31));
		set("wHa", fonts['P' - 'A'].getChar(5 + 31));
		set("P5", fonts['P' - 'A'].getChar(6 + 31));
		set("TAw", fonts['P' - 'A'].getChar(6 + 31));
		set("nfw", fonts['P' - 'A'].getChar(6 + 31));
		set("P6", fonts['P' - 'A'].getChar(7 + 31));
		set("aHa", fonts['P' - 'A'].getChar(7 + 31));
		set("P7", fonts['P' - 'A'].getChar(8 + 31));
		set("P8", fonts['P' - 'A'].getChar(9 + 31));
		set("xrw", fonts['P' - 'A'].getChar(9 + 31));
		set("P9", fonts['P' - 'A'].getChar(10 + 31));
		set("P10", fonts['P' - 'A'].getChar(11 + 31));
		set("P11", fonts['P' - 'A'].getChar(12 + 31));
		set("Q1", fonts['Q' - 'A'].getChar(1 + 31));
		set("st", fonts['Q' - 'A'].getChar(1 + 31));
		set("Q2", fonts['Q' - 'A'].getChar(2 + 31));
		set("wz", fonts['Q' - 'A'].getChar(2 + 31));
		set("Q3", fonts['Q' - 'A'].getChar(3 + 31));
		set("Q4", fonts['Q' - 'A'].getChar(4 + 31));
		set("Q5", fonts['Q' - 'A'].getChar(5 + 31));
		set("Q6", fonts['Q' - 'A'].getChar(6 + 31));
		set("qrsw", fonts['Q' - 'A'].getChar(6 + 31));
		set("qrs", fonts['Q' - 'A'].getChar(6 + 31));
		set("Q7", fonts['Q' - 'A'].getChar(7 + 31));
		set("R1", fonts['R' - 'A'].getChar(1 + 31));
		set("xAwt", fonts['R' - 'A'].getChar(1 + 31));
		set("xAt", fonts['R' - 'A'].getChar(1 + 31));
		set("R2", fonts['R' - 'A'].getChar(2 + 31));
		set("R3", fonts['R' - 'A'].getChar(3 + 31));
		set("R4", fonts['R' - 'A'].getChar(4 + 31));
		set("Htp", fonts['R' - 'A'].getChar(4 + 31));
		set("R5", fonts['R' - 'A'].getChar(5 + 31));
		set("kAp", fonts['R' - 'A'].getChar(5 + 31));
		set("kp", fonts['R' - 'A'].getChar(5 + 31));
		set("R6", fonts['R' - 'A'].getChar(6 + 31));
		set("R7", fonts['R' - 'A'].getChar(7 + 31));
		set("snTr", fonts['R' - 'A'].getChar(7 + 31));
		set("R8", fonts['R' - 'A'].getChar(8 + 31));
		set("nTr", fonts['R' - 'A'].getChar(8 + 31));
		set("R9", fonts['R' - 'A'].getChar(9 + 31));
		set("bd", fonts['R' - 'A'].getChar(9 + 31));
		set("R10", fonts['R' - 'A'].getChar(10 + 31));
		set("R11", fonts['R' - 'A'].getChar(11 + 31));
		set("dd", fonts['R' - 'A'].getChar(11 + 31));
		set("Dd", fonts['R' - 'A'].getChar(11 + 31));
		set("R12", fonts['R' - 'A'].getChar(12 + 31));
		set("R13", fonts['R' - 'A'].getChar(13 + 31));
		set("R14", fonts['R' - 'A'].getChar(14 + 31));
		set("imnt", fonts['R' - 'A'].getChar(14 + 31));
		set("R15", fonts['R' - 'A'].getChar(15 + 31));
		set("iAb", fonts['R' - 'A'].getChar(15 + 31));
		set("R16", fonts['R' - 'A'].getChar(16 + 31));
		set("wx", fonts['R' - 'A'].getChar(16 + 31));
		set("R17", fonts['R' - 'A'].getChar(17 + 31));
		set("R18", fonts['R' - 'A'].getChar(18 + 31));
		set("R19", fonts['R' - 'A'].getChar(19 + 31));
		set("R20", fonts['R' - 'A'].getChar(20 + 31));
		set("R21", fonts['R' - 'A'].getChar(21 + 31));
		set("R22", fonts['R' - 'A'].getChar(22 + 31));
		set("xm", fonts['R' - 'A'].getChar(22 + 31));
		set("R23", fonts['R' - 'A'].getChar(23 + 31));
		set("R24", fonts['R' - 'A'].getChar(24 + 31));
		set("R25", fonts['R' - 'A'].getChar(25 + 31));
		set("S1", fonts['S' - 'A'].getChar(1 + 31));
		set("HDt", fonts['S' - 'A'].getChar(1 + 31));
		set("S2", fonts['S' - 'A'].getChar(2 + 31));
		set("S3", fonts['S' - 'A'].getChar(3 + 31));
		set("dSrt", fonts['S' - 'A'].getChar(3 + 31));
		set("S4", fonts['S' - 'A'].getChar(4 + 31));
		set("S5", fonts['S' - 'A'].getChar(5 + 31));
		set("S6", fonts['S' - 'A'].getChar(6 + 31));
		set("sxmty", fonts['S' - 'A'].getChar(6 + 31));
		set("S7", fonts['S' - 'A'].getChar(7 + 31));
		set("xprS", fonts['S' - 'A'].getChar(7 + 31));
		set("S8", fonts['S' - 'A'].getChar(8 + 31));
		set("Atf", fonts['S' - 'A'].getChar(8 + 31));
		set("S9", fonts['S' - 'A'].getChar(9 + 31));
		set("Swty", fonts['S' - 'A'].getChar(9 + 31));
		set("S10", fonts['S' - 'A'].getChar(10 + 31));
		set("mDH", fonts['S' - 'A'].getChar(10 + 31));
		set("S11", fonts['S' - 'A'].getChar(11 + 31));
		set("wsx", fonts['S' - 'A'].getChar(11 + 31));
		set("S12", fonts['S' - 'A'].getChar(12 + 31));
		set("nbw", fonts['S' - 'A'].getChar(12 + 31));
		set("S13", fonts['S' - 'A'].getChar(13 + 31));
		set("S14", fonts['S' - 'A'].getChar(14 + 31));
		set("S14A", fonts['S' - 'A'].getChar(15 + 31));
		set("S15", fonts['S' - 'A'].getChar(16 + 31));
		set("tHn", fonts['S' - 'A'].getChar(16 + 31));
		set("THn", fonts['S' - 'A'].getChar(16 + 31));
		set("S16", fonts['S' - 'A'].getChar(17 + 31));
		set("S17", fonts['S' - 'A'].getChar(18 + 31));
		set("S18", fonts['S' - 'A'].getChar(19 + 31));
		set("mnit", fonts['S' - 'A'].getChar(19 + 31));
		set("S19", fonts['S' - 'A'].getChar(20 + 31));
		set("sDAw", fonts['S' - 'A'].getChar(20 + 31));
		set("S20", fonts['S' - 'A'].getChar(21 + 31));
		set("xtm", fonts['S' - 'A'].getChar(21 + 31));
		set("S21", fonts['S' - 'A'].getChar(22 + 31));
		set("S22", fonts['S' - 'A'].getChar(23 + 31));
		set("sT", fonts['S' - 'A'].getChar(23 + 31));
		set("S17A", fonts['S' - 'A'].getChar(24 + 31));
		set("S23", fonts['S' - 'A'].getChar(25 + 31));
		set("dmD", fonts['S' - 'A'].getChar(25 + 31));
		set("S24", fonts['S' - 'A'].getChar(26 + 31));
		set("Tz", fonts['S' - 'A'].getChar(26 + 31));
		set("S25", fonts['S' - 'A'].getChar(27 + 31));
		set("S26", fonts['S' - 'A'].getChar(28 + 31));
		set("Sndyt", fonts['S' - 'A'].getChar(28 + 31));
		set("S27", fonts['S' - 'A'].getChar(30 + 31));
		set("mnxt", fonts['S' - 'A'].getChar(30 + 31));
		set("S28", fonts['S' - 'A'].getChar(31 + 31));
		set("S29", fonts['S' - 'A'].getChar(32 + 31));
		set("S30", fonts['S' - 'A'].getChar(33 + 31));
		set("sf", fonts['S' - 'A'].getChar(33 + 31));
		set("S31", fonts['S' - 'A'].getChar(34 + 31));
		set("S32", fonts['S' - 'A'].getChar(35 + 31));
		set("siA", fonts['S' - 'A'].getChar(35 + 31));
		set("S33", fonts['S' - 'A'].getChar(36 + 31));
		set("Tb", fonts['S' - 'A'].getChar(36 + 31));
		set("S34", fonts['S' - 'A'].getChar(37 + 31));
		set("anx", fonts['S' - 'A'].getChar(37 + 31));
		set("V39", fonts['S' - 'A'].getChar(38 + 31));
		set("S35", fonts['S' - 'A'].getChar(39 + 31));
		set("Swt", fonts['S' - 'A'].getChar(39 + 31));
		set("S36", fonts['S' - 'A'].getChar(40 + 31));
		set("S37", fonts['S' - 'A'].getChar(41 + 31));
		set("xw", fonts['S' - 'A'].getChar(41 + 31));
		set("S38", fonts['S' - 'A'].getChar(42 + 31));
		set("HqA", fonts['S' - 'A'].getChar(42 + 31));
		set("S39", fonts['S' - 'A'].getChar(43 + 31));
		set("awt", fonts['S' - 'A'].getChar(43 + 31));
		set("S40", fonts['S' - 'A'].getChar(44 + 31));
		set("wAs", fonts['S' - 'A'].getChar(44 + 31));
		set("S41", fonts['S' - 'A'].getChar(45 + 31));
		set("Dam", fonts['S' - 'A'].getChar(45 + 31));
		set("S42", fonts['S' - 'A'].getChar(46 + 31));
		set("abA", fonts['S' - 'A'].getChar(46 + 31));
		set("sxm", fonts['S' - 'A'].getChar(46 + 31));
		set("xrp", fonts['S' - 'A'].getChar(46 + 31));
		set("S43", fonts['S' - 'A'].getChar(47 + 31));
		set("md", fonts['S' - 'A'].getChar(47 + 31));
		set("S44", fonts['S' - 'A'].getChar(48 + 31));
		set("Ams", fonts['S' - 'A'].getChar(48 + 31));
		set("S45", fonts['S' - 'A'].getChar(49 + 31));
		set("nxxw", fonts['S' - 'A'].getChar(49 + 31));
		set("T1", fonts['T' - 'A'].getChar(1 + 31));
		set("T2", fonts['T' - 'A'].getChar(2 + 31));
		set("T3", fonts['T' - 'A'].getChar(3 + 31));
		set("HD", fonts['T' - 'A'].getChar(3 + 31));
		set("T4", fonts['T' - 'A'].getChar(4 + 31));
		set("T5", fonts['T' - 'A'].getChar(5 + 31));
		set("T6", fonts['T' - 'A'].getChar(6 + 31));
		set("HDD", fonts['T' - 'A'].getChar(6 + 31));
		set("T7", fonts['T' - 'A'].getChar(7 + 31));
		set("T7A", fonts['T' - 'A'].getChar(8 + 31));
		set("T8", fonts['T' - 'A'].getChar(9 + 31));
		set("T8A", fonts['T' - 'A'].getChar(10 + 31));
		set("T9", fonts['T' - 'A'].getChar(11 + 31));
		set("pd", fonts['T' - 'A'].getChar(11 + 31));
		set("T9A", fonts['T' - 'A'].getChar(12 + 31));
		set("T10", fonts['T' - 'A'].getChar(13 + 31));
		set("pD", fonts['T' - 'A'].getChar(13 + 31));
		set("Aa32", fonts['T' - 'A'].getChar(14 + 31));
		set("T11", fonts['T' - 'A'].getChar(15 + 31));
		set("zin", fonts['T' - 'A'].getChar(15 + 31));
		set("zwn", fonts['T' - 'A'].getChar(15 + 31));
		set("sXr", fonts['T' - 'A'].getChar(15 + 31));
		set("T12", fonts['T' - 'A'].getChar(16 + 31));
		set("Ai", fonts['T' - 'A'].getChar(16 + 31));
		set("Ar", fonts['T' - 'A'].getChar(16 + 31));
		set("rwd", fonts['T' - 'A'].getChar(16 + 31));
		set("rwD", fonts['T' - 'A'].getChar(16 + 31));
		set("T13", fonts['T' - 'A'].getChar(17 + 31));
		set("rs", fonts['T' - 'A'].getChar(17 + 31));
		set("T14", fonts['T' - 'A'].getChar(18 + 31));
		set("qmA", fonts['T' - 'A'].getChar(18 + 31));
		set("T15", fonts['T' - 'A'].getChar(19 + 31));
		set("T16", fonts['T' - 'A'].getChar(20 + 31));
		set("T17", fonts['T' - 'A'].getChar(21 + 31));
		set("wrrt", fonts['T' - 'A'].getChar(21 + 31));
		set("T18", fonts['T' - 'A'].getChar(22 + 31));
		set("Sms", fonts['T' - 'A'].getChar(22 + 31));
		set("T19", fonts['T' - 'A'].getChar(23 + 31));
		set("qs", fonts['T' - 'A'].getChar(23 + 31));
		set("T20", fonts['T' - 'A'].getChar(24 + 31));
		set("T21", fonts['T' - 'A'].getChar(25 + 31));
		set("wa", fonts['T' - 'A'].getChar(25 + 31));
		set("T22", fonts['T' - 'A'].getChar(26 + 31));
		set("sn", fonts['T' - 'A'].getChar(26 + 31));
		set("T23", fonts['T' - 'A'].getChar(27 + 31));
		set("T24", fonts['T' - 'A'].getChar(28 + 31));
		set("iH", fonts['T' - 'A'].getChar(28 + 31));
		set("T25", fonts['T' - 'A'].getChar(29 + 31));
		set("DbA", fonts['T' - 'A'].getChar(29 + 31));
		set("T26", fonts['T' - 'A'].getChar(30 + 31));
		set("T27", fonts['T' - 'A'].getChar(31 + 31));
		set("T28", fonts['T' - 'A'].getChar(32 + 31));
		set("Xr", fonts['T' - 'A'].getChar(32 + 31));
		set("T29", fonts['T' - 'A'].getChar(33 + 31));
		set("nmt", fonts['T' - 'A'].getChar(33 + 31));
		set("T30", fonts['T' - 'A'].getChar(34 + 31));
		set("T31", fonts['T' - 'A'].getChar(35 + 31));
		set("sSm", fonts['T' - 'A'].getChar(35 + 31));
		set("T32", fonts['T' - 'A'].getChar(36 + 31));
		set("T33", fonts['T' - 'A'].getChar(37 + 31));
		set("T34", fonts['T' - 'A'].getChar(38 + 31));
		set("nm", fonts['T' - 'A'].getChar(38 + 31));
		set("T35", fonts['T' - 'A'].getChar(39 + 31));
		set("U1", fonts['U' - 'A'].getChar(1 + 31));
		set("mA", fonts['U' - 'A'].getChar(1 + 31));
		set("U2", fonts['U' - 'A'].getChar(2 + 31));
		set("U3", fonts['U' - 'A'].getChar(3 + 31));
		set("U4", fonts['U' - 'A'].getChar(4 + 31));
		set("U5", fonts['U' - 'A'].getChar(5 + 31));
		set("U6", fonts['U' - 'A'].getChar(6 + 31));
		set("mr", fonts['U' - 'A'].getChar(6 + 31));
		set("U7", fonts['U' - 'A'].getChar(7 + 31));
		set("U8", fonts['U' - 'A'].getChar(8 + 31));
		set("U9", fonts['U' - 'A'].getChar(9 + 31));
		set("U10", fonts['U' - 'A'].getChar(10 + 31));
		set("it", fonts['U' - 'A'].getChar(10 + 31));
		set("U11", fonts['U' - 'A'].getChar(11 + 31));
		set("HqAt", fonts['U' - 'A'].getChar(11 + 31));
		set("U12", fonts['U' - 'A'].getChar(12 + 31));
		set("U13", fonts['U' - 'A'].getChar(14 + 31));
		set("hb", fonts['U' - 'A'].getChar(14 + 31));
		set("Sna", fonts['U' - 'A'].getChar(14 + 31));
		set("U14", fonts['U' - 'A'].getChar(15 + 31));
		set("U15", fonts['U' - 'A'].getChar(16 + 31));
		set("tm", fonts['U' - 'A'].getChar(16 + 31));
		set("U16", fonts['U' - 'A'].getChar(17 + 31));
		set("biA", fonts['U' - 'A'].getChar(17 + 31));
		set("U17", fonts['U' - 'A'].getChar(18 + 31));
		set("grg", fonts['U' - 'A'].getChar(18 + 31));
		set("U18", fonts['U' - 'A'].getChar(19 + 31));
		set("U19", fonts['U' - 'A'].getChar(20 + 31));
		set("U20", fonts['U' - 'A'].getChar(21 + 31));
		set("U21", fonts['U' - 'A'].getChar(22 + 31));
		set("stp", fonts['U' - 'A'].getChar(22 + 31));
		set("U22", fonts['U' - 'A'].getChar(23 + 31));
		set("mnx", fonts['U' - 'A'].getChar(23 + 31));
		set("U23", fonts['U' - 'A'].getChar(24 + 31));
		set("Ab", fonts['U' - 'A'].getChar(24 + 31));
		set("U24", fonts['U' - 'A'].getChar(25 + 31));
		set("Hmt", fonts['U' - 'A'].getChar(25 + 31));
		set("U25", fonts['U' - 'A'].getChar(26 + 31));
		set("U26", fonts['U' - 'A'].getChar(27 + 31));
		set("wbA", fonts['U' - 'A'].getChar(27 + 31));
		set("U27", fonts['U' - 'A'].getChar(28 + 31));
		set("U28", fonts['U' - 'A'].getChar(29 + 31));
		set("DA", fonts['U' - 'A'].getChar(29 + 31));
		set("U29", fonts['U' - 'A'].getChar(30 + 31));
		set("U30", fonts['U' - 'A'].getChar(31 + 31));
		set("U31", fonts['U' - 'A'].getChar(32 + 31));
		set("rtH", fonts['U' - 'A'].getChar(32 + 31));
		set("U32", fonts['U' - 'A'].getChar(33 + 31));
		set("zmn", fonts['U' - 'A'].getChar(33 + 31));
		set("U33", fonts['U' - 'A'].getChar(34 + 31));
		set("ti", fonts['U' - 'A'].getChar(34 + 31));
		set("U34", fonts['U' - 'A'].getChar(35 + 31));
		set("xsf", fonts['U' - 'A'].getChar(35 + 31));
		set("U35", fonts['U' - 'A'].getChar(36 + 31));
		set("Aa23", fonts['U' - 'A'].getChar(37 + 31));
		set("Aa24", fonts['U' - 'A'].getChar(38 + 31));
		set("U36", fonts['U' - 'A'].getChar(39 + 31));
		set("Hm", fonts['U' - 'A'].getChar(39 + 31));
		set("U37", fonts['U' - 'A'].getChar(40 + 31));
		set("U38", fonts['U' - 'A'].getChar(41 + 31));
		set("mxAt", fonts['U' - 'A'].getChar(41 + 31));
		set("U39", fonts['U' - 'A'].getChar(42 + 31));
		set("U40", fonts['U' - 'A'].getChar(43 + 31));
		set("U41", fonts['U' - 'A'].getChar(44 + 31));
		set("V1", fonts['V' - 'A'].getChar(1 + 31));
		set("St", fonts['V' - 'A'].getChar(1 + 31));
		set("Snt", fonts['V' - 'A'].getChar(1 + 31));
		set("100", fonts['V' - 'A'].getChar(1 + 31));
		set("V2", fonts['V' - 'A'].getChar(2 + 31));
		set("sTA", fonts['V' - 'A'].getChar(2 + 31));
		set("V3", fonts['V' - 'A'].getChar(3 + 31));
		set("sTAw", fonts['V' - 'A'].getChar(3 + 31));
		set("V4", fonts['V' - 'A'].getChar(4 + 31));
		set("wA", fonts['V' - 'A'].getChar(4 + 31));
		set("V5", fonts['V' - 'A'].getChar(5 + 31));
		set("snT", fonts['V' - 'A'].getChar(5 + 31));
		set("V6", fonts['V' - 'A'].getChar(6 + 31));
		set("V7", fonts['V' - 'A'].getChar(7 + 31));
		set("Sn", fonts['V' - 'A'].getChar(7 + 31));
		set("V8", fonts['V' - 'A'].getChar(8 + 31));
		set("V9", fonts['V' - 'A'].getChar(9 + 31));
		set("V10", fonts['V' - 'A'].getChar(10 + 31));
		set("V11", fonts['V' - 'A'].getChar(11 + 31));
		set("V12", fonts['V' - 'A'].getChar(12 + 31));
		set("arq", fonts['V' - 'A'].getChar(12 + 31));
		set("V13", fonts['V' - 'A'].getChar(13 + 31));
		set("T", fonts['V' - 'A'].getChar(13 + 31));
		set("V14", fonts['V' - 'A'].getChar(14 + 31));
		set("V15", fonts['V' - 'A'].getChar(15 + 31));
		set("iTi", fonts['V' - 'A'].getChar(15 + 31));
		set("V16", fonts['V' - 'A'].getChar(16 + 31));
		set("V17", fonts['V' - 'A'].getChar(17 + 31));
		set("V19", fonts['V' - 'A'].getChar(19 + 31));
		set("V18", fonts['V' - 'A'].getChar(18 + 31));
		set("mDt", fonts['V' - 'A'].getChar(19 + 31));
		set("XAr", fonts['V' - 'A'].getChar(19 + 31));
		set("TmA", fonts['V' - 'A'].getChar(19 + 31));
		set("V20", fonts['V' - 'A'].getChar(20 + 31));
		set("10", fonts['V' - 'A'].getChar(20 + 31));
		set("mD", fonts['V' - 'A'].getChar(20 + 31));
		set("V21", fonts['V' - 'A'].getChar(21 + 31));
		set("V22", fonts['V' - 'A'].getChar(22 + 31));
		set("mH", fonts['V' - 'A'].getChar(22 + 31));
		set("V23", fonts['V' - 'A'].getChar(23 + 31));
		set("V24", fonts['V' - 'A'].getChar(24 + 31));
		set("wD", fonts['V' - 'A'].getChar(24 + 31));
		set("V25", fonts['V' - 'A'].getChar(25 + 31));
		set("V26", fonts['V' - 'A'].getChar(26 + 31));
		set("aD", fonts['V' - 'A'].getChar(26 + 31));
		set("V27", fonts['V' - 'A'].getChar(27 + 31));
		set("V28", fonts['V' - 'A'].getChar(28 + 31));
		set("V29", fonts['V' - 'A'].getChar(29 + 31));
		set("wAH", fonts['V' - 'A'].getChar(29 + 31));
		set("sk", fonts['V' - 'A'].getChar(29 + 31));
		set("V30", fonts['V' - 'A'].getChar(30 + 31));
		set("nb", fonts['V' - 'A'].getChar(30 + 31));
		set("V31", fonts['V' - 'A'].getChar(31 + 31));
		set("V31A", fonts['V' - 'A'].getChar(32 + 31));
		set("V32", fonts['V' - 'A'].getChar(33 + 31));
		set("msn", fonts['V' - 'A'].getChar(33 + 31));
		set("V33", fonts['V' - 'A'].getChar(34 + 31));
		set("sSr", fonts['V' - 'A'].getChar(34 + 31));
		set("V34", fonts['V' - 'A'].getChar(35 + 31));
		set("V35", fonts['V' - 'A'].getChar(36 + 31));
		set("V36", fonts['V' - 'A'].getChar(37 + 31));
		set("V37", fonts['V' - 'A'].getChar(38 + 31));
		set("V38", fonts['V' - 'A'].getChar(39 + 31));
		set("idr", fonts['V' - 'A'].getChar(38 + 31));
		set("W1", fonts['W' - 'A'].getChar(1 + 31));
		set("W2", fonts['W' - 'A'].getChar(2 + 31));
		set("bAs", fonts['W' - 'A'].getChar(2 + 31));
		set("W3", fonts['W' - 'A'].getChar(3 + 31));
		set("Hb", fonts['W' - 'A'].getChar(3 + 31));
		set("W4", fonts['W' - 'A'].getChar(4 + 31));
		set("W5", fonts['W' - 'A'].getChar(5 + 31));
		set("W6", fonts['W' - 'A'].getChar(6 + 31));
		set("W7", fonts['W' - 'A'].getChar(7 + 31));
		set("W8", fonts['W' - 'A'].getChar(8 + 31));
		set("W9", fonts['W' - 'A'].getChar(9 + 31));
		set("Xnm", fonts['W' - 'A'].getChar(9 + 31));
		set("W10", fonts['W' - 'A'].getChar(10 + 31));
		set("iab", fonts['W' - 'A'].getChar(10 + 31));
		set("W10A", fonts['W' - 'A'].getChar(11 + 31));
		set("Aa4", fonts['W' - 'A'].getChar(12 + 31));
		set("W11", fonts['W' - 'A'].getChar(13 + 31));
		set("nst", fonts['W' - 'A'].getChar(13 + 31));
		set("W12", fonts['W' - 'A'].getChar(14 + 31));
		set("W13", fonts['W' - 'A'].getChar(15 + 31));
		set("W14", fonts['W' - 'A'].getChar(16 + 31));
		set("Hz", fonts['W' - 'A'].getChar(16 + 31));
		set("W15", fonts['W' - 'A'].getChar(17 + 31));
		set("W16", fonts['W' - 'A'].getChar(18 + 31));
		set("W17", fonts['W' - 'A'].getChar(19 + 31));
		set("xnt", fonts['W' - 'A'].getChar(19 + 31));
		set("W18", fonts['W' - 'A'].getChar(20 + 31));
		set("W19", fonts['W' - 'A'].getChar(21 + 31));
		set("mi", fonts['W' - 'A'].getChar(21 + 31));
		set("W20", fonts['W' - 'A'].getChar(22 + 31));
		set("W21", fonts['W' - 'A'].getChar(23 + 31));
		set("W22", fonts['W' - 'A'].getChar(24 + 31));
		set("Hnqt", fonts['W' - 'A'].getChar(24 + 31));
		set("W23", fonts['W' - 'A'].getChar(25 + 31));
		set("W24", fonts['W' - 'A'].getChar(26 + 31));
		set("nw", fonts['W' - 'A'].getChar(26 + 31));
		set("W25", fonts['W' - 'A'].getChar(27 + 31));
		set("ini", fonts['W' - 'A'].getChar(27 + 31));
		set("X1", fonts['X' - 'A'].getChar(1 + 31));
		set("X2", fonts['X' - 'A'].getChar(2 + 31));
		set("X3", fonts['X' - 'A'].getChar(3 + 31));
		set("X4", fonts['X' - 'A'].getChar(4 + 31));
		set("X5", fonts['X' - 'A'].getChar(6 + 31));
		set("X6", fonts['X' - 'A'].getChar(7 + 31));
		set("X7", fonts['X' - 'A'].getChar(8 + 31));
		set("X8", fonts['X' - 'A'].getChar(9 + 31));
		set("rdi", fonts['X' - 'A'].getChar(9 + 31));
		set("di", fonts['X' - 'A'].getChar(9 + 31));
		set("Y1", fonts['Y' - 'A'].getChar(1 + 31));
		set("Y1v", fonts['Y' - 'A'].getChar(9 + 31));
		set("mDAt", fonts['Y' - 'A'].getChar(1 + 31));
		set("Y2", fonts['Y' - 'A'].getChar(2 + 31));
		set("Y3", fonts['Y' - 'A'].getChar(3 + 31));
		set("zS", fonts['Y' - 'A'].getChar(3 + 31));
		set("mnhd", fonts['Y' - 'A'].getChar(3 + 31));
		set("Y4", fonts['Y' - 'A'].getChar(4 + 31));
		set("Y5", fonts['Y' - 'A'].getChar(5 + 31));
		set("mn", fonts['Y' - 'A'].getChar(5 + 31));
		set("Y6", fonts['Y' - 'A'].getChar(6 + 31));
		set("ibA", fonts['Y' - 'A'].getChar(6 + 31));
		set("Y7", fonts['Y' - 'A'].getChar(7 + 31));
		set("Y8", fonts['Y' - 'A'].getChar(8 + 31));
		set("zSSt", fonts['Y' - 'A'].getChar(8 + 31));
		set("Z1", fonts['Z' - 'A'].getChar(1 + 31));
		set("Z2", fonts['Z' - 'A'].getChar(2 + 31));
		set("Z4A", fonts['Z' - 'A'].getChar(24 + 31));
		set("Z3", fonts['Z' - 'A'].getChar(3 + 31));
		set("Z3A", fonts['Z' - 'A'].getChar(4 + 31));
		set("N33A", fonts['Z' - 'A'].getChar(5 + 31));
		set("Z4", fonts['Z' - 'A'].getChar(6 + 31));
		set("y", fonts['Z' - 'A'].getChar(6 + 31));
		set("Z5", fonts['Z' - 'A'].getChar(7 + 31));
		set("Z6", fonts['Z' - 'A'].getChar(8 + 31));
		set("Z7", fonts['Z' - 'A'].getChar(9 + 31));
		set("Z8", fonts['Z' - 'A'].getChar(10 + 31));
		set("Z9", fonts['Z' - 'A'].getChar(13 + 31));
		set("Z10", fonts['Z' - 'A'].getChar(14 + 31));
		set("Z11", fonts['Z' - 'A'].getChar(15 + 31));
		set("imi", fonts['Z' - 'A'].getChar(15 + 31));
		set("wnm", fonts['Z' - 'A'].getChar(15 + 31));
		set("`", fonts['Z' - 'A'].getChar(16 + 31));
		set("Ff1", fonts['Z' - 'A'].getChar(16 + 31));
		set("Z12", fonts['Z' - 'A'].getChar(19 + 31));
		set("Z30", fonts['Z' - 'A'].getChar(32 + 31));
		//set("Z98A", fonts['Z' - 'A'].getChar(16 + 31));
		//set("Z99A", fonts['Z' - 'A'].getChar(12 + 31));
		set("Aa1", fonts[26].getChar(1 + 31));
		set("Aa2", fonts[26].getChar(2 + 31));
		set("Aa3", fonts[26].getChar(3 + 31));
		set("Aa5", fonts[26].getChar(4 + 31));
		set("Hp", fonts[26].getChar(4 + 31));
		set("Aa6", fonts[26].getChar(5 + 31));
		set("Aa7", fonts[26].getChar(6 + 31));
		set("Aa8", fonts[26].getChar(7 + 31));
		set("qn", fonts[26].getChar(7 + 31));
		set("Aa9", fonts[26].getChar(8 + 31));
		set("Aa10", fonts[26].getChar(9 + 31));
		set("Aa11", fonts[26].getChar(10 + 31));
		set("mAa", fonts[26].getChar(10 + 31));
		set("Aa12", fonts[26].getChar(11 + 31));
		set("Aa13", fonts[26].getChar(12 + 31));
		set("im", fonts[26].getChar(12 + 31));
		set("gs", fonts[26].getChar(12 + 31));
		set("Aa14", fonts[26].getChar(13 + 31));
		set("Aa15", fonts[26].getChar(14 + 31));
		set("Aa16", fonts[26].getChar(15 + 31));
		set("Aa17", fonts[26].getChar(16 + 31));
		set("sA", fonts[26].getChar(16 + 31));
		set("Aa18", fonts[26].getChar(17 + 31));
		set("Aa19", fonts[26].getChar(18 + 31));
		set("Aa20", fonts[26].getChar(19 + 31));
		set("apr", fonts[26].getChar(19 + 31));
		set("Aa21", fonts[26].getChar(20 + 31));
		set("wDa", fonts[26].getChar(20 + 31));
		set("Aa22", fonts[26].getChar(21 + 31));
		set("Aa25", fonts[26].getChar(22 + 31));
		set("Aa26", fonts[26].getChar(23 + 31));
		set("Aa27", fonts[26].getChar(24 + 31));
		set("nD", fonts[26].getChar(24 + 31));
		set("Aa28", fonts[26].getChar(25 + 31));
		set("qd", fonts[26].getChar(25 + 31));
		set("Aa29", fonts[26].getChar(26 + 31));
		set("Aa30", fonts[26].getChar(27 + 31));
		set("Xkr", fonts[26].getChar(27 + 31));
		set("Aa31", fonts[26].getChar(28 + 31));
		set("o", fonts['Z' - 'A'].getChar(17 + 31));
		set("O", fonts['Z' - 'A'].getChar(17 + 31));
		//
		//set("1", fonts['Z' - 'A'].getChar(1 + 31));
		//set("3", fonts['Z' - 'A'].getChar(2 + 31));
		//set("2", fonts['Z' - 'A'].getChar(20 + 31));
		set("2", fonts['Z' - 'A'].getChar(20 + 31));
		//set("4", fonts['Z' - 'A'].getChar(21 + 31));
		set("4", fonts['Z' - 'A'].getChar(21 + 31));
		//set("5", fonts['Z' - 'A'].getChar(22 + 31));	
		set("5", fonts['Z' - 'A'].getChar(22 + 31));		
		//
		set("nTrw", fonts['R' - 'A'].getChar(57));
		set("nn", fonts['M' - 'A'].getChar(76));
	}

	public ShapeChar get(String code) {
		return (ShapeChar) codes.get(code);
	}

	public void set(String code, ShapeChar s) {
		hasNewSigns= true;
		codes.put(code, s);
	}

	public ShapeChar getSmallBody(String code) {
		// No small body shape currently.
		return null;
	}
	
	/**
	 * A temporary method, which WILL MOVE  WHEN THE FONTS ARE STORED IN A DATABASE.
	 * IMPORTANT : CHANGE THE FONT HANDLING SYSTEM.
	 * @return the set of codes.
	 */
	public Set getCodes()
	{
		hasNewSigns= false;
		return codes.keySet();
	}
	
	public boolean hasNewSigns() {	
		return hasNewSigns;
	}
} // HieroglyphicFontManager
