#!/bin/sh

export CLASSPATH
CLASSPATH=../../dist/jsesh.jar

for i in ../../lib/*.jar; do 
	CLASSPATH="$CLASSPATH:$i"
done

export LD_LIBRARY_PATH=/usr/local/lib

java -Xmx128M -Xrunjmp:filter=jsesh jsesh.mdcDisplayer.swing.application.MDCDisplayerAppli

