/**
 * Code for reading texts written in the Manuel de Codage format.
 *
 * <p>Most of the time, you will use the
 * {@link jsesh.parser.MDCParserModelGenerator} class, which can be used to
 * build an in-memory model of the manuel de codage text:
 *
 * <pre>
 * MDCParserModelGenerator m = new MDCParserModelGenerator();
 * Reader r = new StringReader("p*t:pt");
 * TopItemList l = m.parse(r);
 * </pre>
 *
 * <p>All classes used in the model generated by this method are part of the
 * package {@link jsesh.model}.
 *
 * <p>Yet, if you want to have more control over your parsing process, you can
 * use the class {@link jsesh.parser.MDCParserFacade}. You should supply a
 * {@code jsesh.model.api.MDCBuilder} to indicate exactly what you want to do
 * when you meet some Manuel de Codage construct.
 */
package jsesh.parser;
