/**
 * Code for reading texts written in the Manuel de Codage format.
 *
 * <p>Most of the time, you will use the
 * {@link jsesh.parser.MDCParserModelGenerator} class, which can be used to
 * build an in-memory model of the manuel de codage text:
 *
 * <pre>
 * MDCParserModelGenerator m = new MDCParserModelGenerator();
 * Reader r = new StringReader("p*t:pt");
 * TopItemList l = m.parse(r);
 * </pre>
 *
 * <p>All classes used in the model generated by this method are part of the
 * package {@link jsesh.model}.
 *
 * <p>If instead you want a literal, uninterpreted record of what was parsed
 * (for instance to write a source-level tool), use
 * {@link jsesh.parser.MDCParserAstGenerator}, which builds an {@link jsesh.parser.ast.AstDocument}.
 * That AST is walkable with {@link jsesh.parser.ast.AstVisitor}. See the
 * package {@link jsesh.parser.ast} for details.
 *
 * <p>Both {@code MDCParserModelGenerator} and {@code MDCParserAstGenerator}
 * are backed by {@link jsesh.parser.handmade.MDCHandmadeParser}, a
 * hand-written recursive descent parser for the Manuel de Codage grammar.
 */
package jsesh.parser;
