/*
 * JTagEditor.java
 *
 * Created on 27 septembre 2007, 19:46
 */

package jsesh.utilitysoftwares.signinfoeditor.ui;

import net.miginfocom.swing.MigLayout;

/**
 *
 * @author  rosmord
 */
public class JTagEditor extends javax.swing.JPanel {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 2253271717049260331L;

	/** Creates new form JTagEditor */
    public JTagEditor() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tagNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tagNameList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelTable = new javax.swing.JTable();
        labelAddButton = new javax.swing.JButton();
        labelRemoveButton = new javax.swing.JButton();
        tagAddButton = new javax.swing.JButton();
        tagRemoveButton = new javax.swing.JButton();
        labelField = new javax.swing.JTextField();

        tagNameField.setColumns(10);

        jLabel1.setText("Tag");
        
        jScrollPane1.setViewportView(tagNameList);

        jLabel2.setText("Tag labels");

        labelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(labelTable);

        labelAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jsesh/utilitysoftwares/signinfoeditor/icons/edit_add.png"))); // NOI18N

        labelRemoveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jsesh/utilitysoftwares/signinfoeditor/icons/edit_remove.png"))); // NOI18N

        tagAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jsesh/utilitysoftwares/signinfoeditor/icons/edit_add.png"))); // NOI18N

        tagRemoveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jsesh/utilitysoftwares/signinfoeditor/icons/edit_remove.png"))); // NOI18N

        setLayout(new MigLayout("insets dialog, wrap 6", "[][][][][grow,fill][]", "[][grow]"));
        // Row 1: input row
        add(jLabel1);
        add(tagNameField);
        add(tagAddButton, "gapright 18");
        add(jLabel2);
        add(labelField, "growx");
        add(labelAddButton);
        // Row 2: scrollpane row (grows vertically)
        add(jScrollPane1, "span 2, grow");
        add(tagRemoveButton, "top, gapright 18");
        add(jScrollPane2, "span 2, grow");
        add(labelRemoveButton, "top");
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton labelAddButton;
    private javax.swing.JTextField labelField;
    private javax.swing.JButton labelRemoveButton;
    private javax.swing.JTable labelTable;
    private javax.swing.JButton tagAddButton;
    private javax.swing.JTextField tagNameField;
    private javax.swing.JList tagNameList;
    private javax.swing.JButton tagRemoveButton;
    // End of variables declaration//GEN-END:variables

	/**
	 * @return the labelAddButton
	 */
	public javax.swing.JButton getLabelAddButton() {
		return labelAddButton;
	}

	/**
	 * @return the labelField
	 */
	public javax.swing.JTextField getLabelField() {
		return labelField;
	}

	/**
	 * @return the labelRemoveButton
	 */
	public javax.swing.JButton getLabelRemoveButton() {
		return labelRemoveButton;
	}

	/**
	 * @return the labelTable
	 */
	public javax.swing.JTable getLabelTable() {
		return labelTable;
	}

	/**
	 * @return the tagAddButton
	 */
	public javax.swing.JButton getTagAddButton() {
		return tagAddButton;
	}

	/**
	 * @return the tagNameField
	 */
	public javax.swing.JTextField getTagNameField() {
		return tagNameField;
	}

	/**
	 * @return the tagNameList
	 */
	public javax.swing.JList getTagNameList() {
		return tagNameList;
	}

	/**
	 * @return the tagRemoveButton
	 */
	public javax.swing.JButton getTagRemoveButton() {
		return tagRemoveButton;
	}
    
}
