name: Test Release

on:
  push:
    tags:
      - 'test-release-*'

jobs:
  build-mac-m1:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build macOS DMG
        run: ./gradlew jpackage

      - name: Rename DMG
        run: for f in jsesh-installer/build/jpackage/JSesh-*.dmg; do mv "$f" "${f/JSesh-/JSesh-m1-}"; done

      - uses: actions/upload-artifact@v6
        with:
          name: macos-m1.dmg
          path: jsesh-installer/build/jpackage/*.dmg

  build-mac-intel:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build macOS DMG
        env:
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        run: ./gradlew jpackage

      - name: Rename DMG
        run: for f in jsesh-installer/build/jpackage/JSesh-*.dmg; do mv "$f" "${f/JSesh-/JSesh-intel-}"; done

      - uses: actions/upload-artifact@v6
        with:
          name: macos-intel.dmg
          path: jsesh-installer/build/jpackage/*.dmg

  release:
    needs: [build-mac-m1, build-mac-intel]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v6
        with:
          path: artifacts

      - uses: softprops/action-gh-release@v3
        with:
          files: |
            artifacts/macos-m1.dmg/*.dmg
            artifacts/macos-intel.dmg/*.dmg
            